name: Release

on:
  release:
    types: [published]

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: test $(npm ls -l | head -n 1 | sed 's/.*@/v/') = {{ github.ref_name }}
  build:
    needs: check-package-version
    strategy:
      matrix:
        include:
        - os: windows
          os_short: win
        - os: macos
          os_short: mac
    runs-on: ${{ matrix.os }}-latest
    steps:
    - run: git config --global core.autocrlf false
      if: matrix.os == 'windows'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run electron:build -- --publish never
    - run: node archive.mjs ${{ matrix.os_short }} ${{ github.ref_name }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os}}-release
        path: dist_electron/release-*.zip
